---
title: "Module 6: RELMIN TRACK BADGE ACTIVITY"
author: "LASER Institute"
date: today 
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
theme:
  light: simplex
  dark: cyborg
editor: visual
jupyter: python3
bibliography: lit/references.bib
---

**LASER INSTITUTE RELMIN TRACK BADGE ACTIVITY**

1.  Please write a short essay in response to the following question. How could you apply either Correlation Mining, Association Rule Mining, or Sequential Pattern Mining to solve (just one) real problem in your research or in practice?

<!-- -->

2.  Input that essay to ChatGPT 4o or another Large Language Model of your preference, following the initial prompt:\
    \
    You are Ryan Baker, a researcher with extremely detailed knowledge of Correlation Mining, Association Rule Mining, and Sequential Pattern Mining and an expert on their use within educational data mining research and practice. Please give feedback on the following essay written by an advanced doctoral student. Please give them feedback on the core ideas and their application on the research or real-world problem; do not give academic paper feedback such as a recommendation to add citations. Give only constructive, negative feedback:

<!-- -->

3.  How would you modify your essay, if at all, in response to that feedback?

<!-- -->

4.  Input your modified essay to ChatGPT 4o or another Large Language Model of your preference, following the initial prompt:\
    \
    You are Haiying Li, an award-winning university instructor who has enhanced online learning programs using relationship mining methods such as Correlation Mining, Association Rule Mining, and Sequential Pattern Mining, and who has spent hundreds of hours watching and interacting with students using those curricula, as well as reviewing student assignments, course outcomes, and teaching evaluations. Please give feedback on the following essay written by an advanced doctoral student. Please give them feedback on the core ideas and their application on the research or real-world problem; do not give academic paper feedback such as a recommendation to add citations. Do not make scientifically inaccurate recommendations, such as recommending paying attention to learning styles. Give only constructive, negative feedback:

<!-- -->

5.  How would you modify your essay, if at all, in response to that feedback?

<!-- -->

6.  Input your modified essay to ChatGPT 4o or another Large Language Model of your preference, following the initial prompt:\
    \
    You are Tanvi, a thoughtful and highly intelligent masters student who nonetheless sometimes struggles with learning activities in areas she is not familiar with. You have just spent the last semester using a course or learning system, enhanced using the following essay. You have been asked to give your reflections on that learning system and how to make it better. Do not make scientifically inaccurate recommendations, such as recommending paying attention to learning styles. You say:\
    \
    (If this prompt does not fit your context of use, please modify it to make it fit!)

<!-- -->

7.  How would you modify your essay, if at all, in response to that feedback?
